export const specialties = [
  { value: "129", label: "Adult Immunization Clinic" },
  { value: "189", label: "Allergy Clinic" },
  { value: "114", label: "Anaesthesiology" },
  { value: "184", label: "Blood Bank" },
  { value: "70", label: "Bone Marrow Transplantation" },
  { value: "58", label: "Centre for Cancer Care" },
  { value: "54", label: "Centre for Cardiac Care" },
  { value: "63", label: "Centre for Neuro Care" },
  { value: "67", label: "Centre for Orthopedic Care" },
  { value: "199", label: "Child Development Centre" },
  { value: "88", label: "Clinical Genetics" },
  { value: "71", label: "Clinical Hematology" },
  { value: "112", label: "Clinical Nutrition" },
  { value: "91", label: "Clinical Psychology" },
  { value: "128", label: "Collagen and Lung Clinic" },
  { value: "105", label: "Dental" },
  { value: "127", label: "Dental Implant Clinic" },
  { value: "86", label: "Dermatology" },
  { value: "104", label: "ENT" },
  { value: "198", label: "Emergency" },
  { value: "97", label: "Endocrinology" },
  { value: "335", label: "Evening Consultations Clinic" },
  { value: "121", label: "Fitness Clinic" },
  { value: "96", label: "Gastroenterology Surgery" },
  { value: "95", label: "Gastroenterology and Liver Care" },
  { value: "85", label: "General Medicine / Internal Medicine" },
  { value: "170", label: "General Surgery" },
  { value: "76", label: "Gynecology" },
  { value: "204", label: "Heart Valve Clinic" },
  { value: "77", label: "IVF & Infertility" },
  { value: "115", label: "Imaging" },
  { value: "89", label: "Infectious Diseases" },
  { value: "113", label: "Interventional Radiology" },
  { value: "200", label: "Irritable Bowel Disease Clinic" },
  { value: "116", label: "Lab Medicine" },
  { value: "122", label: "Lupus Clinic" },
  { value: "107", label: "Minimal Access Surgery" },
  { value: "338", label: "Myasthenia Gravis Clinic" },
  { value: "317", label: "Nephrology" },
  { value: "117", label: "Nuclear Medicine" },
  { value: "333", label: "Ocular Immunology Clinic" },
  { value: "100", label: "Ophthalmology" },
  { value: "78", label: "Paediatric Care" },
  { value: "111", label: "Pain Management" },
  { value: "202", label: "Pain Management Clinic" },
  { value: "119", label: "Palliative Care" },
  { value: "110", label: "Physiotherapy & Rehabilitation" },
  { value: "201", label: "Plastic Surgery" },
  { value: "87", label: "Psychiatry" },
  { value: "92", label: "Pulmonary Medicine" },
  { value: "99", label: "Rheumatology" },
  { value: "108", label: "Robotic Surgery" },
  { value: "125", label: "Tobacco Cessation Clinic" },
  { value: "130", label: "Travel Medicine Clinic" },
  { value: "75", label: "Urology" },
  { value: "203", label: "Uveitis Clinic" },
  { value: "120", label: "Vulva Clinic" },
  { value: "330", label: "Women’s Cancer Screening Clinic" },
];

export const images = [
  {
    src: "/images/filler/1.jpg",
    alt: "1",
  },
  {
    src: "/images/filler/1.png",
    alt: "1",
  },
  {
    src: "/images/filler/1.png",
    alt: "1",
  },
  {
    src: "/images/filler/1.png",
    alt: "1",
  },
  {
    src: "/images/filler/1.jpg",
    alt: "1",
  },
  {
    src: "/images/filler/1.png",
    alt: "2",
  },
  {
    src: "/images/filler/2.jpg",
    alt: "3",
  },
  {
    src: "/images/filler/3.jpeg",
    alt: "4",
  },
  {
    src: "/images/filler/hero.png",
    alt: "5",
  },
];

export const links = [
  { href: "/appointment", label: 'Consulation' },
  { href: "/inpatient", label: 'Admission Process' },
  { href: "/insurance", label: 'Insurance' },
  { href: "/emergency", label: '24*7 Emergency' },
  { href: "/short-stay-services", label: 'Short Stay Services' }
]